spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: admin_password_123

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: INFO
    dev.keyclockuser: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

keycloak:
  auth-server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8081}
  realm: ${KEYCLOAK_REALM:user-service}
  client-id: ${KEYCLOAK_CLIENT_ID:user-service-rest-api}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  admin:
    realm: master
    client-id: admin-cli
    username : admin
    password : admin_password
#  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
#  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin_password}
#  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}
#  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
